In [1]:
import numpy as np

In [36]:
n = 3
m = 1
H = 2
x = np.array([[0],
              [0.5],
              [1]])
w = np.array([[-0.03283963, -0.04337479]])
u = np.array([-0.01133743,  0.08387997])
v = np.array([[0.0123421 ],
              [0.08048297]])
a_ref = ([[-0.01133743, 0.08387997],
          [-0.02775725, 0.06219257],
          [-0.04417707, 0.04050517]])
N_ref = np.array([[0.00661098],
                  [0.00466286],
                  [0.00271474]])
dN_dw_ref = np.array([[0.01851315, 0.12072446]])
dN_du_ref = np.array([0.0370263 , 0.24144892])
dN_dv_ref = np.array([[-0.08327175],
                      [ 0.18657771]])
dN_dx_ref = np.array([[-0.00389624],
                      [-0.00389624],
                      [-0.00389624]])

In [17]:
x.shape, w.shape

((3, 1), (1, 2))

In [37]:
a = x@w + u

In [38]:
a - a_ref

array([[0.00000000e+00, 0.00000000e+00],
       [5.00000000e-09, 5.00000000e-09],
       [9.99999999e-09, 9.99999999e-09]])

In [43]:
v.shape, a.shape

((2, 1), (3, 2))

In [45]:
N = a@v
N

array([[0.00661098],
       [0.00466286],
       [0.00271474]])

In [46]:
v.shape, w.shape

((2, 1), (1, 2))

In [59]:
dN_dx = np.zeros((n, m))
dN_dx[0, 0] = v[0]*w[0, 0] + v[1]*w[0, 1]
dN_dx[1, 0] = v[0]*w[0, 0] + v[1]*w[0, 1]
dN_dx[2, 0] = v[0]*w[0, 0] + v[1]*w[0, 1]
dN_dx

array([[-0.00389624],
       [-0.00389624],
       [-0.00389624]])

In [34]:
dN_dx - dN_dx_ref

array([[-1.9197493e-09],
       [-1.9197493e-09],
       [-1.9197493e-09]])

In [64]:
dN_dw = np.zeros((n, H))
for i in range(n):
    for k in range(H):
        dN_dw[i, k] = v[k]*x[i, 0]
dN_dw

array([[0.        , 0.        ],
       [0.00617105, 0.04024149],
       [0.0123421 , 0.08048297]])

In [66]:
dN_du = np.zeros((n, H))
for i in range(n):
    for k in range(H):
        dN_du[i, k] = v[k]
dN_du

array([[0.0123421 , 0.08048297],
       [0.0123421 , 0.08048297],
       [0.0123421 , 0.08048297]])

In [67]:
dN_dv = np.zeros((n, H))
for i in range(n):
    for k in range(H):
        dN_dv[i, k] = a[i, k]
dN_dv

array([[-0.01133743,  0.08387997],
       [-0.02775724,  0.06219257],
       [-0.04417706,  0.04050518]])