In [1]:
import numpy as np

In [2]:
x = np.linspace(0, 1, 11)

In [3]:
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [4]:
xsub = x

In [5]:
xsub is x

True

In [6]:
xsub = x[0:2]

In [7]:
xsub.base

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [8]:
xsub

array([0. , 0.1])

In [9]:
p = np.linspace(0, 1, 33)

In [13]:
np.hsplit(p, 3)

[array([0.     , 0.03125, 0.0625 , 0.09375, 0.125  , 0.15625, 0.1875 ,
        0.21875, 0.25   , 0.28125, 0.3125 ]),
 array([0.34375, 0.375  , 0.40625, 0.4375 , 0.46875, 0.5    , 0.53125,
        0.5625 , 0.59375, 0.625  , 0.65625]),
 array([0.6875 , 0.71875, 0.75   , 0.78125, 0.8125 , 0.84375, 0.875  ,
        0.90625, 0.9375 , 0.96875, 1.     ])]

In [14]:
w, u, v = np.hsplit(p, 3)

In [15]:
w

array([0.     , 0.03125, 0.0625 , 0.09375, 0.125  , 0.15625, 0.1875 ,
       0.21875, 0.25   , 0.28125, 0.3125 ])

In [16]:
w = np.array([0, 1, 2, 3])
x = np.linspace(0, 1, 4)

In [17]:
w

array([0, 1, 2, 3])

In [18]:
x

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [19]:
w*x

array([0.        , 0.33333333, 1.33333333, 3.        ])

In [20]:
np.outer(w, x)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.66666667, 1.        ],
       [0.        , 0.66666667, 1.33333333, 2.        ],
       [0.        , 1.        , 2.        , 3.        ]])

In [21]:
np.outer(w, x) == np.outer(x, w)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [22]:
w = np.linspace(0, 1, 3)

In [23]:
x = np.linspace(0, 1, 4)

In [24]:
w

array([0. , 0.5, 1. ])

In [25]:
x

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [26]:
np.outer(w,x)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.        , 0.33333333, 0.66666667, 1.        ]])

In [27]:
np.outer(x,w)

array([[0.        , 0.        , 0.        ],
       [0.        , 0.16666667, 0.33333333],
       [0.        , 0.33333333, 0.66666667],
       [0.        , 0.5       , 1.        ]])