In [2]:
import numpy as np
import tensorflow as tf

In [5]:
x = [0.,         0.,         0.,         0.,         0.,
     0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
     0.66666667, 0.66666667, 0.66666667, 0.66666667, 0.66666667,
     1.,         1.,         1.,         1.,         1.        ]

In [6]:
y = [0., 0.25, 0.5, 0.75, 1.,
     0., 0.25, 0.5, 0.75, 1.,
     0., 0.25, 0.5, 0.75, 1.,
     0., 0.25, 0.5, 0.75, 1.]

In [16]:
xy = np.array(list(zip(x, y)))

In [9]:
w = np.array([[-0.03283963, -0.04337479, -0.0333208],
              [ 0.08916026,  0.01477627,  0.03570686]])

In [11]:
u = np.array([-0.01133743, 0.08387997, -0.06781313])

In [14]:
v = np.array([[ 0.0123421 ],
              [ 0.08048297],
              [-0.04861869]])

In [15]:
v

array([[ 0.0123421 ],
       [ 0.08048297],
       [-0.04861869]])

In [19]:
xy.shape, w.shape

((20, 2), (2, 3))

In [32]:
z = xy@w + u

In [35]:
z

array([[-1.13374300e-02,  8.38799700e-02, -6.78131300e-02],
       [ 1.09526350e-02,  8.75740375e-02, -5.88864150e-02],
       [ 3.32427000e-02,  9.12681050e-02, -4.99597000e-02],
       [ 5.55327650e-02,  9.49621725e-02, -4.10329850e-02],
       [ 7.78228300e-02,  9.86562400e-02, -3.21062700e-02],
       [-2.22839732e-02,  6.94217068e-02, -7.89200632e-02],
       [ 6.09177613e-06,  7.31157743e-02, -6.99933482e-02],
       [ 2.22961568e-02,  7.68098418e-02, -6.10666332e-02],
       [ 4.45862218e-02,  8.05039093e-02, -5.21399182e-02],
       [ 6.68762868e-02,  8.41979768e-02, -4.32132032e-02],
       [-3.32305168e-02,  5.49634432e-02, -9.00269968e-02],
       [-1.09404518e-02,  5.86575107e-02, -8.11002818e-02],
       [ 1.13496132e-02,  6.23515782e-02, -7.21735668e-02],
       [ 3.36396782e-02,  6.60456457e-02, -6.32468518e-02],
       [ 5.59297432e-02,  6.97397132e-02, -5.43201368e-02],
       [-4.41770600e-02,  4.05051800e-02, -1.01133930e-01],
       [-2.18869950e-02,  4.41992475e-02

In [52]:
def sigma(z):
    return 1/(1 + np.exp(-z))

def dsigma_dz(z):
    s = sigma(z)
    return s*(1 - s)

In [53]:
s = sigma(z)
s1 = dsigma_dz(z)

In [56]:
N = a@v

In [57]:
# Define the form of the trial solution.

# Precompute constants.
c1 = np.exp(-1)

def Y_trial(xy, N):
    x = xy[:, 0]
    y = xy[:, 1]
    A = (
        (1 - x)*y**3
        + x*(1 + y**3)*c1
        + (1 - y)*x*(np.exp(-x) - c1)
        + y*(np.exp(-x)*(x + 1) - (1 - x + 2*x*c1))
    )
    P = x*(1 - x)*y*(1 - y)
    Y = A + P*N[:, 0]
    return Y

In [58]:
Y_trial(xy, N)

array([0.        , 0.015625  , 0.125     , 0.421875  , 1.        ,
       0.23884377, 0.23400369, 0.30248331, 0.51827599, 0.95537508,
       0.34227808, 0.33603597, 0.38336507, 0.53850495, 0.8556952 ,
       0.36787944, 0.37362756, 0.41386437, 0.52307858, 0.73575888])

In [75]:
s1.shape, xy.shape, w.shape, v.shape, 

((20, 3), (20, 2), (2, 3), (3, 1))

In [93]:
H = 3
nxt = 4
nyt = 5
nt = nxt*nyt

dN_dx = np.zeros((nt,))
for i in range(nt):
    for k in range(H):
        dN_dx += v[k, 0]*s1[i, k]*w[0, k]

In [94]:
dN_dx

array([-0.01136767, -0.01136767, -0.01136767, -0.01136767, -0.01136767,
       -0.01136767, -0.01136767, -0.01136767, -0.01136767, -0.01136767,
       -0.01136767, -0.01136767, -0.01136767, -0.01136767, -0.01136767,
       -0.01136767, -0.01136767, -0.01136767, -0.01136767, -0.01136767])