In [1]:
import numpy as np
import tensorflow as tf

In [3]:
xy = tf.Variable([1.0, 2.0])

In [4]:
xy[0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [6]:
with tf.GradientTape() as tape1:
    z = xy[0]**2 + xy[1]**2

In [7]:
z

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [8]:
tape1.gradient(z, xy)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 4.], dtype=float32)>

In [12]:
with tf.GradientTape() as tape2:
    with tf.GradientTape() as tape1:
        z = xy[0]**2 + xy[1]**2
    dz_dxy = tape1.gradient(z, xy)

In [13]:
dz_dxy

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 4.], dtype=float32)>

In [14]:
tape2.gradient(dz_dxy, xy)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>